export const Countries = [
  {
    id: 1,
    name: "American Samoa",
    abv: "AS",
    language: "English",
    latlong: "-14.33333333,-170",
    currency: "$",
    flag: "https://flagcdn.com/as.svg",
    areaCode: "+1684",
  },
  {
    id: 2,
    name: "Peru",
    abv: "PE",
    language: "Aymara",
    latlong: "-10,-76",
    currency: "S/ ",
    flag: "https://flagcdn.com/pe.svg",
    areaCode: "+51",
  },
  {
    id: 3,
    name: "Tonga",
    abv: "TO",
    language: "English",
    latlong: "-20,-175",
    currency: "T$",
    flag: "https://flagcdn.com/to.svg",
    areaCode: "+676",
  },
  {
    id: 4,
    name: "Mayotte",
    abv: "YT",
    language: "French",
    latlong: "-12.83333333,45.16666666",
    currency: "€",
    flag: "https://flagcdn.com/yt.svg",
    areaCode: "+262",
  },
  {
    id: 5,
    name: "Panama",
    abv: "PA",
    language: "Spanish",
    latlong: "9,-80",
    currency: "B/.",
    flag: "https://flagcdn.com/pa.svg",
    areaCode: "+507",
  },
  {
    id: 6,
    name: "Madagascar",
    abv: "MG",
    language: "French",
    latlong: "-20,47",
    currency: "Ar",
    flag: "https://flagcdn.com/mg.svg",
    areaCode: "+261",
  },
  {
    id: 7,
    name: "Belgium",
    abv: "BE",
    language: "German",
    latlong: "50.83333333,4",
    currency: "€",
    flag: "https://flagcdn.com/be.svg",
    areaCode: "+32",
  },
  {
    id: 8,
    name: "Central African Republic",
    abv: "CF",
    language: "French",
    latlong: "7,21",
    currency: "Fr",
    flag: "https://flagcdn.com/cf.svg",
    areaCode: "+236",
  },
  {
    id: 9,
    name: "Hungary",
    abv: "HU",
    language: "Hungarian",
    latlong: "47,20",
    currency: "Ft",
    flag: "https://flagcdn.com/hu.svg",
    areaCode: "+36",
  },
  {
    id: 10,
    name: "Mongolia",
    abv: "MN",
    language: "Mongolian",
    latlong: "46,105",
    currency: "₮",
    flag: "https://flagcdn.com/mn.svg",
    areaCode: "+976",
  },
  {
    id: 11,
    name: "Saudi Arabia",
    abv: "SA",
    language: "Arabic",
    latlong: "25,45",
    currency: "ر.س",
    flag: "https://flagcdn.com/sa.svg",
    areaCode: "+966",
  },
  {
    id: 12,
    name: "Eswatini",
    abv: "SZ",
    language: "English",
    latlong: "-26.5,31.5",
    currency: "L",
    flag: "https://flagcdn.com/sz.svg",
    areaCode: "+268",
  },
  {
    id: 13,
    name: "Uganda",
    abv: "UG",
    language: "English",
    latlong: "1,32",
    currency: "Sh",
    flag: "https://flagcdn.com/ug.svg",
    areaCode: "+256",
  },
  {
    id: 14,
    name: "Paraguay",
    abv: "PY",
    language: "Guaraní",
    latlong: "-23,-58",
    currency: "₲",
    flag: "https://flagcdn.com/py.svg",
    areaCode: "+595",
  },
  {
    id: 15,
    name: "Cameroon",
    abv: "CM",
    language: "English",
    latlong: "6,12",
    currency: "Fr",
    flag: "https://flagcdn.com/cm.svg",
    areaCode: "+237",
  },
  {
    id: 16,
    name: "France",
    abv: "FR",
    language: "French",
    latlong: "46,2",
    currency: "€",
    flag: "https://flagcdn.com/fr.svg",
    areaCode: "+33",
  },
  {
    id: 17,
    name: "Togo",
    abv: "TG",
    language: "French",
    latlong: "8,1.16666666",
    currency: "Fr",
    flag: "https://flagcdn.com/tg.svg",
    areaCode: "+228",
  },
  {
    id: 18,
    name: "Mauritius",
    abv: "MU",
    language: "English",
    latlong: "-20.28333333,57.55",
    currency: "₨",
    flag: "https://flagcdn.com/mu.svg",
    areaCode: "+230",
  },
  {
    id: 19,
    name: "Cook Islands",
    abv: "CK",
    language: "English",
    latlong: "-21.23333333,-159.76666666",
    currency: "$",
    flag: "https://flagcdn.com/ck.svg",
    areaCode: "+682",
  },
  {
    id: 20,
    name: "Palau",
    abv: "PW",
    language: "English",
    latlong: "7.5,134.5",
    currency: "$",
    flag: "https://flagcdn.com/pw.svg",
    areaCode: "+680",
  },
  {
    id: 21,
    name: "Nepal",
    abv: "NP",
    language: "Nepali",
    latlong: "28,84",
    currency: "₨",
    flag: "https://flagcdn.com/np.svg",
    areaCode: "+977",
  },
  {
    id: 22,
    name: "New Zealand",
    abv: "NZ",
    language: "English",
    latlong: "-41,174",
    currency: "$",
    flag: "https://flagcdn.com/nz.svg",
    areaCode: "+64",
  },
  {
    id: 23,
    name: "Pitcairn Islands",
    abv: "PN",
    language: "English",
    latlong: "-25.06666666,-130.1",
    currency: "$",
    flag: "https://flagcdn.com/pn.svg",
    areaCode: "+64",
  },
  {
    id: 24,
    name: "Seychelles",
    abv: "SC",
    language: "Seychellois Creole",
    latlong: "-4.58333333,55.66666666",
    currency: "₨",
    flag: "https://flagcdn.com/sc.svg",
    areaCode: "+248",
  },
  {
    id: 25,
    name: "United Arab Emirates",
    abv: "AE",
    language: "Arabic",
    latlong: "24,54",
    currency: "د.إ",
    flag: "https://flagcdn.com/ae.svg",
    areaCode: "+971",
  },
  {
    id: 26,
    name: "Belarus",
    abv: "BY",
    language: "Belarusian",
    latlong: "53,28",
    currency: "Br",
    flag: "https://flagcdn.com/by.svg",
    areaCode: "+375",
  },
  {
    id: 27,
    name: "Dominican Republic",
    abv: "DO",
    language: "Spanish",
    latlong: "19,-70.66666666",
    currency: "$",
    flag: "https://flagcdn.com/do.svg",
    areaCode: "+1809",
  },
  {
    id: 28,
    name: "Libya",
    abv: "LY",
    language: "Arabic",
    latlong: "25,17",
    currency: "ل.د",
    flag: "https://flagcdn.com/ly.svg",
    areaCode: "+218",
  },
  {
    id: 29,
    name: "Tokelau",
    abv: "TK",
    language: "English",
    latlong: "-9,-172",
    currency: "$",
    flag: "https://flagcdn.com/tk.svg",
    areaCode: "+690",
  },
  {
    id: 30,
    name: "Croatia",
    abv: "HR",
    language: "Croatian",
    latlong: "45.16666666,15.5",
    currency: "€",
    flag: "https://flagcdn.com/hr.svg",
    areaCode: "+385",
  },
  {
    id: 31,
    name: "Philippines",
    abv: "PH",
    language: "English",
    latlong: "13,122",
    currency: "₱",
    flag: "https://flagcdn.com/ph.svg",
    areaCode: "+63",
  },
  {
    id: 32,
    name: "Albania",
    abv: "AL",
    language: "Albanian",
    latlong: "41,20",
    currency: "L",
    flag: "https://flagcdn.com/al.svg",
    areaCode: "+355",
  },
  {
    id: 33,
    name: "Bouvet Island",
    abv: "BV",
    language: "Norwegian",
    latlong: "54.4208,3.3464",
    currency: "",
    flag: "https://flagcdn.com/bv.svg",
    areaCode: "+47",
  },
  {
    id: 34,
    name: "Indonesia",
    abv: "ID",
    language: "Indonesian",
    latlong: "-5,120",
    currency: "Rp",
    flag: "https://flagcdn.com/id.svg",
    areaCode: "+62",
  },
  {
    id: 35,
    name: "Thailand",
    abv: "TH",
    language: "Thai",
    latlong: "15,100",
    currency: "฿",
    flag: "https://flagcdn.com/th.svg",
    areaCode: "+66",
  },
  {
    id: 36,
    name: "Latvia",
    abv: "LV",
    language: "Latvian",
    latlong: "57,25",
    currency: "€",
    flag: "https://flagcdn.com/lv.svg",
    areaCode: "+371",
  },
  {
    id: 37,
    name: "Ecuador",
    abv: "EC",
    language: "Spanish",
    latlong: "-2,-77.5",
    currency: "$",
    flag: "https://flagcdn.com/ec.svg",
    areaCode: "+593",
  },
  {
    id: 38,
    name: "Kenya",
    abv: "KE",
    language: "English",
    latlong: "1,38",
    currency: "Sh",
    flag: "https://flagcdn.com/ke.svg",
    areaCode: "+254",
  },
  {
    id: 39,
    name: "Liberia",
    abv: "LR",
    language: "English",
    latlong: "6.5,-9.5",
    currency: "$",
    flag: "https://flagcdn.com/lr.svg",
    areaCode: "+231",
  },
  {
    id: 40,
    name: "British Virgin Islands",
    abv: "VG",
    language: "English",
    latlong: "18.431383,-64.62305",
    currency: "$",
    flag: "https://flagcdn.com/vg.svg",
    areaCode: "+1284",
  },
  {
    id: 41,
    name: "San Marino",
    abv: "SM",
    language: "Italian",
    latlong: "43.76666666,12.41666666",
    currency: "€",
    flag: "https://flagcdn.com/sm.svg",
    areaCode: "+378",
  },
  {
    id: 42,
    name: "India",
    abv: "IN",
    language: "English",
    latlong: "20,77",
    currency: "₹",
    flag: "https://flagcdn.com/in.svg",
    areaCode: "+91",
  },
  {
    id: 43,
    name: "Bahrain",
    abv: "BH",
    language: "Arabic",
    latlong: "26,50.55",
    currency: ".د.ب",
    flag: "https://flagcdn.com/bh.svg",
    areaCode: "+973",
  },
  {
    id: 44,
    name: "Malawi",
    abv: "MW",
    language: "English",
    latlong: "-13.5,34",
    currency: "MK",
    flag: "https://flagcdn.com/mw.svg",
    areaCode: "+265",
  },
  {
    id: 45,
    name: "Iceland",
    abv: "IS",
    language: "Icelandic",
    latlong: "65,-18",
    currency: "kr",
    flag: "https://flagcdn.com/is.svg",
    areaCode: "+354",
  },
  {
    id: 46,
    name: "Brunei",
    abv: "BN",
    language: "Malay",
    latlong: "4.5,114.66666666",
    currency: "$",
    flag: "https://flagcdn.com/bn.svg",
    areaCode: "+673",
  },
  {
    id: 47,
    name: "French Guiana",
    abv: "GF",
    language: "French",
    latlong: "4,-53",
    currency: "€",
    flag: "https://flagcdn.com/gf.svg",
    areaCode: "+594",
  },
  {
    id: 48,
    name: "Samoa",
    abv: "WS",
    language: "English",
    latlong: "-13.58333333,-172.33333333",
    currency: "T",
    flag: "https://flagcdn.com/ws.svg",
    areaCode: "+685",
  },
  {
    id: 49,
    name: "Georgia",
    abv: "GE",
    language: "Georgian",
    latlong: "42,43.5",
    currency: "₾",
    flag: "https://flagcdn.com/ge.svg",
    areaCode: "+995",
  },
  {
    id: 50,
    name: "Caribbean Netherlands",
    abv: "BQ",
    language: "English",
    latlong: "12.18,-68.25",
    currency: "$",
    flag: "https://flagcdn.com/bq.svg",
    areaCode: "+599",
  },
  {
    id: 51,
    name: "Heard Island and McDonald Islands",
    abv: "HM",
    language: "English",
    latlong: "53.0818,73.5042",
    currency: "",
    flag: "https://flagcdn.com/hm.svg",
    areaCode: "undefined",
  },
  {
    id: 52,
    name: "Papua New Guinea",
    abv: "PG",
    language: "English",
    latlong: "-6,147",
    currency: "K",
    flag: "https://flagcdn.com/pg.svg",
    areaCode: "+675",
  },
  {
    id: 53,
    name: "Ghana",
    abv: "GH",
    language: "English",
    latlong: "8,-2",
    currency: "₵",
    flag: "https://flagcdn.com/gh.svg",
    areaCode: "+233",
  },
  {
    id: 54,
    name: "Afghanistan",
    abv: "AF",
    language: "Dari",
    latlong: "33,65",
    currency: "؋",
    flag: "https://upload.wikimedia.org/wikipedia/commons/5/5c/Flag_of_the_Taliban.svg",
    areaCode: "+93",
  },
  {
    id: 55,
    name: "Costa Rica",
    abv: "CR",
    language: "Spanish",
    latlong: "10,-84",
    currency: "₡",
    flag: "https://flagcdn.com/cr.svg",
    areaCode: "+506",
  },
  {
    id: 56,
    name: "Fiji",
    abv: "FJ",
    language: "English",
    latlong: "17.7134,178.065",
    currency: "$",
    flag: "https://flagcdn.com/fj.svg",
    areaCode: "+679",
  },
  {
    id: 57,
    name: "South Korea",
    abv: "KR",
    language: "Korean",
    latlong: "37,127.5",
    currency: "₩",
    flag: "https://flagcdn.com/kr.svg",
    areaCode: "+82",
  },
  {
    id: 58,
    name: "Taiwan",
    abv: "TW",
    language: "Chinese",
    latlong: "23.5,121",
    currency: "$",
    flag: "https://flagcdn.com/tw.svg",
    areaCode: "+886",
  },
  {
    id: 59,
    name: "Czechia",
    abv: "CZ",
    language: "Czech",
    latlong: "49.75,15.5",
    currency: "Kč",
    flag: "https://flagcdn.com/cz.svg",
    areaCode: "+420",
  },
  {
    id: 60,
    name: "Nicaragua",
    abv: "NI",
    language: "Spanish",
    latlong: "13,-85",
    currency: "C$",
    flag: "https://flagcdn.com/ni.svg",
    areaCode: "+505",
  },
  {
    id: 61,
    name: "Portugal",
    abv: "PT",
    language: "Portuguese",
    latlong: "39.5,-8",
    currency: "€",
    flag: "https://flagcdn.com/pt.svg",
    areaCode: "+351",
  },
  {
    id: 62,
    name: "Chile",
    abv: "CL",
    language: "Spanish",
    latlong: "-30,-71",
    currency: "$",
    flag: "https://flagcdn.com/cl.svg",
    areaCode: "+56",
  },
  {
    id: 63,
    name: "Gambia",
    abv: "GM",
    language: "English",
    latlong: "13.46666666,-16.56666666",
    currency: "D",
    flag: "https://flagcdn.com/gm.svg",
    areaCode: "+220",
  },
  {
    id: 64,
    name: "Belize",
    abv: "BZ",
    language: "Belizean Creole",
    latlong: "17.25,-88.75",
    currency: "$",
    flag: "https://flagcdn.com/bz.svg",
    areaCode: "+501",
  },
  {
    id: 65,
    name: "Maldives",
    abv: "MV",
    language: "Maldivian",
    latlong: "3.25,73",
    currency: ".ރ",
    flag: "https://flagcdn.com/mv.svg",
    areaCode: "+960",
  },
  {
    id: 66,
    name: "Vanuatu",
    abv: "VU",
    language: "Bislama",
    latlong: "-16,167",
    currency: "Vt",
    flag: "https://flagcdn.com/vu.svg",
    areaCode: "+678",
  },
  {
    id: 67,
    name: "Malaysia",
    abv: "MY",
    language: "English",
    latlong: "2.5,112.5",
    currency: "RM",
    flag: "https://flagcdn.com/my.svg",
    areaCode: "+60",
  },
  {
    id: 68,
    name: "Antigua and Barbuda",
    abv: "AG",
    language: "English",
    latlong: "17.05,-61.8",
    currency: "$",
    flag: "https://flagcdn.com/ag.svg",
    areaCode: "+1268",
  },
  {
    id: 69,
    name: "Iran",
    abv: "IR",
    language: "Persian (Farsi)",
    latlong: "32,53",
    currency: "﷼",
    flag: "https://flagcdn.com/ir.svg",
    areaCode: "+98",
  },
  {
    id: 70,
    name: "Russia",
    abv: "RU",
    language: "Russian",
    latlong: "60,100",
    currency: "₽",
    flag: "https://flagcdn.com/ru.svg",
    areaCode: "+73",
  },
  {
    id: 71,
    name: "Kiribati",
    abv: "KI",
    language: "English",
    latlong: "1.41666666,173",
    currency: "$",
    flag: "https://flagcdn.com/ki.svg",
    areaCode: "+686",
  },
  {
    id: 72,
    name: "Martinique",
    abv: "MQ",
    language: "French",
    latlong: "14.666667,-61",
    currency: "€",
    flag: "https://flagcdn.com/mq.svg",
    areaCode: "+596",
  },
  {
    id: 73,
    name: "Bangladesh",
    abv: "BD",
    language: "Bengali",
    latlong: "24,90",
    currency: "৳",
    flag: "https://flagcdn.com/bd.svg",
    areaCode: "+880",
  },
  {
    id: 74,
    name: "Armenia",
    abv: "AM",
    language: "Armenian",
    latlong: "40,45",
    currency: "֏",
    flag: "https://flagcdn.com/am.svg",
    areaCode: "+374",
  },
  {
    id: 75,
    name: "Mexico",
    abv: "MX",
    language: "Spanish",
    latlong: "23,-102",
    currency: "$",
    flag: "https://flagcdn.com/mx.svg",
    areaCode: "+52",
  },
  {
    id: 76,
    name: "Estonia",
    abv: "EE",
    language: "Estonian",
    latlong: "59,26",
    currency: "€",
    flag: "https://flagcdn.com/ee.svg",
    areaCode: "+372",
  },
  {
    id: 77,
    name: "Oman",
    abv: "OM",
    language: "Arabic",
    latlong: "21,57",
    currency: "ر.ع.",
    flag: "https://flagcdn.com/om.svg",
    areaCode: "+968",
  },
  {
    id: 78,
    name: "United States",
    abv: "US",
    language: "English",
    latlong: "38,-97",
    currency: "$",
    flag: "https://flagcdn.com/us.svg",
    areaCode: "+1201",
  },
  {
    id: 79,
    name: "Liechtenstein",
    abv: "LI",
    language: "German",
    latlong: "47.26666666,9.53333333",
    currency: "Fr",
    flag: "https://flagcdn.com/li.svg",
    areaCode: "+423",
  },
  {
    id: 80,
    name: "Bahamas",
    abv: "BS",
    language: "English",
    latlong: "25.0343,-77.3963",
    currency: "$",
    flag: "https://flagcdn.com/bs.svg",
    areaCode: "+1242",
  },
  {
    id: 81,
    name: "Benin",
    abv: "BJ",
    language: "French",
    latlong: "9.5,2.25",
    currency: "Fr",
    flag: "https://flagcdn.com/bj.svg",
    areaCode: "+229",
  },
  {
    id: 82,
    name: "Kosovo",
    abv: "XK",
    language: "Albanian",
    latlong: "42.666667,21.166667",
    currency: "€",
    flag: "https://flagcdn.com/xk.svg",
    areaCode: "+383",
  },
  {
    id: 83,
    name: "Tuvalu",
    abv: "TV",
    language: "English",
    latlong: "-8,178",
    currency: "$",
    flag: "https://flagcdn.com/tv.svg",
    areaCode: "+688",
  },
  {
    id: 84,
    name: "Faroe Islands",
    abv: "FO",
    language: "Danish",
    latlong: "62,-7",
    currency: "kr",
    flag: "https://flagcdn.com/fo.svg",
    areaCode: "+298",
  },
  {
    id: 85,
    name: "Cayman Islands",
    abv: "KY",
    language: "English",
    latlong: "19.3133,-81.2546",
    currency: "$",
    flag: "https://flagcdn.com/ky.svg",
    areaCode: "+1345",
  },
  {
    id: 86,
    name: "Egypt",
    abv: "EG",
    language: "Arabic",
    latlong: "27,30",
    currency: "£",
    flag: "https://flagcdn.com/eg.svg",
    areaCode: "+20",
  },
  {
    id: 87,
    name: "Azerbaijan",
    abv: "AZ",
    language: "Azerbaijani",
    latlong: "40.5,47.5",
    currency: "₼",
    flag: "https://flagcdn.com/az.svg",
    areaCode: "+994",
  },
  {
    id: 88,
    name: "Australia",
    abv: "AU",
    language: "English",
    latlong: "-27,133",
    currency: "$",
    flag: "https://flagcdn.com/au.svg",
    areaCode: "+61",
  },
  {
    id: 89,
    name: "Isle of Man",
    abv: "IM",
    language: "English",
    latlong: "54.25,-4.5",
    currency: "£",
    flag: "https://flagcdn.com/im.svg",
    areaCode: "+44",
  },
  {
    id: 90,
    name: "Ireland",
    abv: "IE",
    language: "English",
    latlong: "53,-8",
    currency: "€",
    flag: "https://flagcdn.com/ie.svg",
    areaCode: "+353",
  },
  {
    id: 91,
    name: "Barbados",
    abv: "BB",
    language: "English",
    latlong: "13.16666666,-59.53333333",
    currency: "$",
    flag: "https://flagcdn.com/bb.svg",
    areaCode: "+1246",
  },
  {
    id: 92,
    name: "El Salvador",
    abv: "SV",
    language: "Spanish",
    latlong: "13.83333333,-88.91666666",
    currency: "$",
    flag: "https://flagcdn.com/sv.svg",
    areaCode: "+503",
  },
  {
    id: 93,
    name: "Guatemala",
    abv: "GT",
    language: "Spanish",
    latlong: "15.5,-90.25",
    currency: "Q",
    flag: "https://flagcdn.com/gt.svg",
    areaCode: "+502",
  },
  {
    id: 94,
    name: "Japan",
    abv: "JP",
    language: "Japanese",
    latlong: "36,138",
    currency: "¥",
    flag: "https://flagcdn.com/jp.svg",
    areaCode: "+81",
  },
  {
    id: 95,
    name: "Vietnam",
    abv: "VN",
    language: "Vietnamese",
    latlong: "16.16666666,107.83333333",
    currency: "₫",
    flag: "https://flagcdn.com/vn.svg",
    areaCode: "+84",
  },
  {
    id: 96,
    name: "Northern Mariana Islands",
    abv: "MP",
    language: "Carolinian",
    latlong: "15.2,145.75",
    currency: "$",
    flag: "https://flagcdn.com/mp.svg",
    areaCode: "+1670",
  },
  {
    id: 97,
    name: "Lithuania",
    abv: "LT",
    language: "Lithuanian",
    latlong: "56,24",
    currency: "€",
    flag: "https://flagcdn.com/lt.svg",
    areaCode: "+370",
  },
  {
    id: 98,
    name: "Saint Lucia",
    abv: "LC",
    language: "English",
    latlong: "13.88333333,-60.96666666",
    currency: "$",
    flag: "https://flagcdn.com/lc.svg",
    areaCode: "+1758",
  },
  {
    id: 99,
    name: "Hong Kong",
    abv: "HK",
    language: "English",
    latlong: "22.267,114.188",
    currency: "$",
    flag: "https://flagcdn.com/hk.svg",
    areaCode: "+852",
  },
  {
    id: 100,
    name: "Angola",
    abv: "AO",
    language: "Portuguese",
    latlong: "-12.5,18.5",
    currency: "Kz",
    flag: "https://flagcdn.com/ao.svg",
    areaCode: "+244",
  },
  {
    id: 101,
    name: "Mozambique",
    abv: "MZ",
    language: "Portuguese",
    latlong: "-18.25,35",
    currency: "MT",
    flag: "https://flagcdn.com/mz.svg",
    areaCode: "+258",
  },
  {
    id: 102,
    name: "Botswana",
    abv: "BW",
    language: "English",
    latlong: "-22,24",
    currency: "P",
    flag: "https://flagcdn.com/bw.svg",
    areaCode: "+267",
  },
  {
    id: 103,
    name: "Germany",
    abv: "DE",
    language: "German",
    latlong: "51,9",
    currency: "€",
    flag: "https://flagcdn.com/de.svg",
    areaCode: "+49",
  },
  {
    id: 104,
    name: "Syria",
    abv: "SY",
    language: "Arabic",
    latlong: "35,38",
    currency: "£",
    flag: "https://flagcdn.com/sy.svg",
    areaCode: "+963",
  },
  {
    id: 105,
    name: "Moldova",
    abv: "MD",
    language: "Romanian",
    latlong: "47,29",
    currency: "L",
    flag: "https://flagcdn.com/md.svg",
    areaCode: "+373",
  },
  {
    id: 106,
    name: "Saint Pierre and Miquelon",
    abv: "PM",
    language: "French",
    latlong: "46.83333333,-56.33333333",
    currency: "€",
    flag: "https://flagcdn.com/pm.svg",
    areaCode: "+508",
  },
  {
    id: 107,
    name: "Guernsey",
    abv: "GG",
    language: "English",
    latlong: "49.46666666,-2.58333333",
    currency: "£",
    flag: "https://flagcdn.com/gg.svg",
    areaCode: "+44",
  },
  {
    id: 108,
    name: "Wallis and Futuna",
    abv: "WF",
    language: "French",
    latlong: "-13.3,-176.2",
    currency: "₣",
    flag: "https://flagcdn.com/wf.svg",
    areaCode: "+681",
  },
  {
    id: 109,
    name: "Poland",
    abv: "PL",
    language: "Polish",
    latlong: "52,20",
    currency: "zł",
    flag: "https://flagcdn.com/pl.svg",
    areaCode: "+48",
  },
  {
    id: 110,
    name: "Trinidad and Tobago",
    abv: "TT",
    language: "English",
    latlong: "10.6918,-61.2225",
    currency: "$",
    flag: "https://flagcdn.com/tt.svg",
    areaCode: "+1868",
  },
  {
    id: 111,
    name: "British Indian Ocean Territory",
    abv: "IO",
    language: "English",
    latlong: "-6,71.5",
    currency: "$",
    flag: "https://flagcdn.com/io.svg",
    areaCode: "+246",
  },
  {
    id: 112,
    name: "Marshall Islands",
    abv: "MH",
    language: "English",
    latlong: "9,168",
    currency: "$",
    flag: "https://flagcdn.com/mh.svg",
    areaCode: "+692",
  },
  {
    id: 113,
    name: "Austria",
    abv: "AT",
    language: "German",
    latlong: "47.33333333,13.33333333",
    currency: "€",
    flag: "https://flagcdn.com/at.svg",
    areaCode: "+43",
  },
  {
    id: 114,
    name: "Kazakhstan",
    abv: "KZ",
    language: "Kazakh",
    latlong: "48.0196,66.9237",
    currency: "₸",
    flag: "https://flagcdn.com/kz.svg",
    areaCode: "+76",
  },
  {
    id: 115,
    name: "Aruba",
    abv: "AW",
    language: "Dutch",
    latlong: "12.5,-69.96666666",
    currency: "ƒ",
    flag: "https://flagcdn.com/aw.svg",
    areaCode: "+297",
  },
  {
    id: 116,
    name: "South Africa",
    abv: "ZA",
    language: "Afrikaans",
    latlong: "-29,24",
    currency: "R",
    flag: "https://flagcdn.com/za.svg",
    areaCode: "+27",
  },
  {
    id: 117,
    name: "Denmark",
    abv: "DK",
    language: "Danish",
    latlong: "56,10",
    currency: "kr",
    flag: "https://flagcdn.com/dk.svg",
    areaCode: "+45",
  },
  {
    id: 118,
    name: "Suriname",
    abv: "SR",
    language: "Dutch",
    latlong: "4,-56",
    currency: "$",
    flag: "https://flagcdn.com/sr.svg",
    areaCode: "+597",
  },
  {
    id: 119,
    name: "Bermuda",
    abv: "BM",
    language: "English",
    latlong: "32.33333333,-64.75",
    currency: "$",
    flag: "https://flagcdn.com/bm.svg",
    areaCode: "+1441",
  },
  {
    id: 120,
    name: "Montserrat",
    abv: "MS",
    language: "English",
    latlong: "16.75,-62.2",
    currency: "$",
    flag: "https://flagcdn.com/ms.svg",
    areaCode: "+1664",
  },
  {
    id: 121,
    name: "Ivory Coast",
    abv: "CI",
    language: "French",
    latlong: "8,-5",
    currency: "Fr",
    flag: "https://flagcdn.com/ci.svg",
    areaCode: "+225",
  },
  {
    id: 122,
    name: "Mauritania",
    abv: "MR",
    language: "Arabic",
    latlong: "20,-12",
    currency: "UM",
    flag: "https://flagcdn.com/mr.svg",
    areaCode: "+222",
  },
  {
    id: 123,
    name: "Sierra Leone",
    abv: "SL",
    language: "English",
    latlong: "8.5,-11.5",
    currency: "Le",
    flag: "https://flagcdn.com/sl.svg",
    areaCode: "+232",
  },
  {
    id: 124,
    name: "Guinea",
    abv: "GN",
    language: "French",
    latlong: "11,-10",
    currency: "Fr",
    flag: "https://flagcdn.com/gn.svg",
    areaCode: "+224",
  },
  {
    id: 125,
    name: "French Polynesia",
    abv: "PF",
    language: "French",
    latlong: "17.6797,149.4068",
    currency: "₣",
    flag: "https://flagcdn.com/pf.svg",
    areaCode: "+689",
  },
  {
    id: 126,
    name: "Pakistan",
    abv: "PK",
    language: "English",
    latlong: "30,70",
    currency: "₨",
    flag: "https://flagcdn.com/pk.svg",
    areaCode: "+92",
  },
  {
    id: 127,
    name: "United States Minor Outlying Islands",
    abv: "UM",
    language: "English",
    latlong: "19.3,166.633333",
    currency: "$",
    flag: "https://flagcdn.com/um.svg",
    areaCode: "+268",
  },
  {
    id: 128,
    name: "Lesotho",
    abv: "LS",
    language: "English",
    latlong: "-29.5,28.5",
    currency: "L",
    flag: "https://flagcdn.com/ls.svg",
    areaCode: "+266",
  },
  {
    id: 129,
    name: "Senegal",
    abv: "SN",
    language: "French",
    latlong: "14,-14",
    currency: "Fr",
    flag: "https://flagcdn.com/sn.svg",
    areaCode: "+221",
  },
  {
    id: 130,
    name: "Tajikistan",
    abv: "TJ",
    language: "Russian",
    latlong: "39,71",
    currency: "ЅМ",
    flag: "https://flagcdn.com/tj.svg",
    areaCode: "+992",
  },
  {
    id: 131,
    name: "Switzerland",
    abv: "CH",
    language: "French",
    latlong: "47,8",
    currency: "Fr.",
    flag: "https://flagcdn.com/ch.svg",
    areaCode: "+41",
  },
  {
    id: 132,
    name: "Eritrea",
    abv: "ER",
    language: "Arabic",
    latlong: "15,39",
    currency: "Nfk",
    flag: "https://flagcdn.com/er.svg",
    areaCode: "+291",
  },
  {
    id: 133,
    name: "French Southern and Antarctic Lands",
    abv: "TF",
    language: "French",
    latlong: "-49.25,69.167",
    currency: "€",
    flag: "https://flagcdn.com/tf.svg",
    areaCode: "+262",
  },
  {
    id: 134,
    name: "Jersey",
    abv: "JE",
    language: "English",
    latlong: "49.25,-2.16666666",
    currency: "£",
    flag: "https://flagcdn.com/je.svg",
    areaCode: "+44",
  },
  {
    id: 135,
    name: "Cambodia",
    abv: "KH",
    language: "Khmer",
    latlong: "13,105",
    currency: "៛",
    flag: "https://flagcdn.com/kh.svg",
    areaCode: "+855",
  },
  {
    id: 136,
    name: "Saint Vincent and the Grenadines",
    abv: "VC",
    language: "English",
    latlong: "13.25,-61.2",
    currency: "$",
    flag: "https://flagcdn.com/vc.svg",
    areaCode: "+1784",
  },
  {
    id: 137,
    name: "Sint Maarten",
    abv: "SX",
    language: "English",
    latlong: "18.033333,-63.05",
    currency: "ƒ",
    flag: "https://flagcdn.com/sx.svg",
    areaCode: "+1721",
  },
  {
    id: 138,
    name: "Vatican City",
    abv: "VA",
    language: "Italian",
    latlong: "41.9,12.45",
    currency: "€",
    flag: "https://flagcdn.com/va.svg",
    areaCode: "+3906698",
  },
  {
    id: 139,
    name: "Uruguay",
    abv: "UY",
    language: "Spanish",
    latlong: "-33,-56",
    currency: "$",
    flag: "https://flagcdn.com/uy.svg",
    areaCode: "+598",
  },
  {
    id: 140,
    name: "Western Sahara",
    abv: "EH",
    language: "Berber",
    latlong: "24.5,-13",
    currency: "دج",
    flag: "https://flagcdn.com/eh.svg",
    areaCode: "+2125288",
  },
  {
    id: 141,
    name: "Cape Verde",
    abv: "CV",
    language: "Portuguese",
    latlong: "16.5388,23.0418",
    currency: "Esc",
    flag: "https://flagcdn.com/cv.svg",
    areaCode: "+238",
  },
  {
    id: 142,
    name: "Italy",
    abv: "IT",
    language: "Italian",
    latlong: "42.83333333,12.83333333",
    currency: "€",
    flag: "https://flagcdn.com/it.svg",
    areaCode: "+39",
  },
  {
    id: 143,
    name: "United Kingdom",
    abv: "GB",
    language: "English",
    latlong: "54,-2",
    currency: "£",
    flag: "https://flagcdn.com/gb.svg",
    areaCode: "+44",
  },
  {
    id: 144,
    name: "Macau",
    abv: "MO",
    language: "Portuguese",
    latlong: "22.16666666,113.55",
    currency: "P",
    flag: "https://flagcdn.com/mo.svg",
    areaCode: "+853",
  },
  {
    id: 145,
    name: "Guyana",
    abv: "GY",
    language: "English",
    latlong: "5,-59",
    currency: "$",
    flag: "https://flagcdn.com/gy.svg",
    areaCode: "+592",
  },
  {
    id: 146,
    name: "Norway",
    abv: "NO",
    language: "Norwegian Nynorsk",
    latlong: "62,10",
    currency: "kr",
    flag: "https://flagcdn.com/no.svg",
    areaCode: "+47",
  },
  {
    id: 147,
    name: "New Caledonia",
    abv: "NC",
    language: "French",
    latlong: "-21.5,165.5",
    currency: "₣",
    flag: "https://flagcdn.com/nc.svg",
    areaCode: "+687",
  },
  {
    id: 148,
    name: "South Sudan",
    abv: "SS",
    language: "English",
    latlong: "7,30",
    currency: "£",
    flag: "https://flagcdn.com/ss.svg",
    areaCode: "+211",
  },
  {
    id: 149,
    name: "Burkina Faso",
    abv: "BF",
    language: "French",
    latlong: "13,-2",
    currency: "Fr",
    flag: "https://flagcdn.com/bf.svg",
    areaCode: "+226",
  },
  {
    id: 150,
    name: "Guadeloupe",
    abv: "GP",
    language: "French",
    latlong: "16.25,-61.583333",
    currency: "€",
    flag: "https://flagcdn.com/gp.svg",
    areaCode: "+590",
  },
  {
    id: 151,
    name: "Lebanon",
    abv: "LB",
    language: "Arabic",
    latlong: "33.83333333,35.83333333",
    currency: "ل.ل",
    flag: "https://flagcdn.com/lb.svg",
    areaCode: "+961",
  },
  {
    id: 152,
    name: "Saint Kitts and Nevis",
    abv: "KN",
    language: "English",
    latlong: "17.33333333,-62.75",
    currency: "$",
    flag: "https://flagcdn.com/kn.svg",
    areaCode: "+1869",
  },
  {
    id: 153,
    name: "Kuwait",
    abv: "KW",
    language: "Arabic",
    latlong: "29.5,45.75",
    currency: "د.ك",
    flag: "https://flagcdn.com/kw.svg",
    areaCode: "+965",
  },
  {
    id: 154,
    name: "South Georgia",
    abv: "GS",
    language: "English",
    latlong: "-54.5,-37",
    currency: "£",
    flag: "https://flagcdn.com/gs.svg",
    areaCode: "+500",
  },
  {
    id: 155,
    name: "Luxembourg",
    abv: "LU",
    language: "German",
    latlong: "49.75,6.16666666",
    currency: "€",
    flag: "https://flagcdn.com/lu.svg",
    areaCode: "+352",
  },
  {
    id: 156,
    name: "Myanmar",
    abv: "MM",
    language: "Burmese",
    latlong: "22,98",
    currency: "Ks",
    flag: "https://flagcdn.com/mm.svg",
    areaCode: "+95",
  },
  {
    id: 157,
    name: "Israel",
    abv: "IL",
    language: "Arabic",
    latlong: "31.47,35.13",
    currency: "₪",
    flag: "https://flagcdn.com/il.svg",
    areaCode: "+972",
  },
  {
    id: 158,
    name: "Turkmenistan",
    abv: "TM",
    language: "Russian",
    latlong: "40,60",
    currency: "m",
    flag: "https://flagcdn.com/tm.svg",
    areaCode: "+993",
  },
  {
    id: 159,
    name: "Greece",
    abv: "GR",
    language: "Greek",
    latlong: "39,22",
    currency: "€",
    flag: "https://flagcdn.com/gr.svg",
    areaCode: "+30",
  },
  {
    id: 160,
    name: "Monaco",
    abv: "MC",
    language: "French",
    latlong: "43.73333333,7.4",
    currency: "€",
    flag: "https://flagcdn.com/mc.svg",
    areaCode: "+377",
  },
  {
    id: 161,
    name: "Venezuela",
    abv: "VE",
    language: "Spanish",
    latlong: "8,-66",
    currency: "Bs.S.",
    flag: "https://flagcdn.com/ve.svg",
    areaCode: "+58",
  },
  {
    id: 162,
    name: "Republic of the Congo",
    abv: "CG",
    language: "French",
    latlong: "-1,15",
    currency: "Fr",
    flag: "https://flagcdn.com/cg.svg",
    areaCode: "+242",
  },
  {
    id: 163,
    name: "Spain",
    abv: "ES",
    language: "Spanish",
    latlong: "40,-4",
    currency: "€",
    flag: "https://flagcdn.com/es.svg",
    areaCode: "+34",
  },
  {
    id: 164,
    name: "Norfolk Island",
    abv: "NF",
    language: "English",
    latlong: "-29.03333333,167.95",
    currency: "$",
    flag: "https://flagcdn.com/nf.svg",
    areaCode: "+672",
  },
  {
    id: 165,
    name: "Dominica",
    abv: "DM",
    language: "English",
    latlong: "15.41666666,-61.33333333",
    currency: "$",
    flag: "https://flagcdn.com/dm.svg",
    areaCode: "+1767",
  },
  {
    id: 166,
    name: "Tunisia",
    abv: "TN",
    language: "Arabic",
    latlong: "34,9",
    currency: "د.ت",
    flag: "https://flagcdn.com/tn.svg",
    areaCode: "+216",
  },
  {
    id: 167,
    name: "Turkey",
    abv: "TR",
    language: "Turkish",
    latlong: "39,35",
    currency: "₺",
    flag: "https://flagcdn.com/tr.svg",
    areaCode: "+90",
  },
  {
    id: 168,
    name: "Colombia",
    abv: "CO",
    language: "Spanish",
    latlong: "4,-72",
    currency: "$",
    flag: "https://flagcdn.com/co.svg",
    areaCode: "+57",
  },
  {
    id: 169,
    name: "Comoros",
    abv: "KM",
    language: "Arabic",
    latlong: "-12.16666666,44.25",
    currency: "Fr",
    flag: "https://flagcdn.com/km.svg",
    areaCode: "+269",
  },
  {
    id: 170,
    name: "Solomon Islands",
    abv: "SB",
    language: "English",
    latlong: "-8,159",
    currency: "$",
    flag: "https://flagcdn.com/sb.svg",
    areaCode: "+677",
  },
  {
    id: 171,
    name: "Saint Barthélemy",
    abv: "BL",
    language: "French",
    latlong: "18.5,-63.41666666",
    currency: "€",
    flag: "https://flagcdn.com/bl.svg",
    areaCode: "+590",
  },
  {
    id: 172,
    name: "Uzbekistan",
    abv: "UZ",
    language: "Russian",
    latlong: "41,64",
    currency: "so'm",
    flag: "https://flagcdn.com/uz.svg",
    areaCode: "+998",
  },
  {
    id: 173,
    name: "Palestine",
    abv: "PS",
    language: "Arabic",
    latlong: "31.9,35.2",
    currency: "E£",
    flag: "https://flagcdn.com/ps.svg",
    areaCode: "+970",
  },
  {
    id: 174,
    name: "Cuba",
    abv: "CU",
    language: "Spanish",
    latlong: "21.5,-80",
    currency: "$",
    flag: "https://flagcdn.com/cu.svg",
    areaCode: "+53",
  },
  {
    id: 175,
    name: "Gabon",
    abv: "GA",
    language: "French",
    latlong: "-1,11.75",
    currency: "Fr",
    flag: "https://flagcdn.com/ga.svg",
    areaCode: "+241",
  },
  {
    id: 176,
    name: "Kyrgyzstan",
    abv: "KG",
    language: "Kyrgyz",
    latlong: "41,75",
    currency: "с",
    flag: "https://flagcdn.com/kg.svg",
    areaCode: "+996",
  },
  {
    id: 177,
    name: "Micronesia",
    abv: "FM",
    language: "English",
    latlong: "6.91666666,158.25",
    currency: "$",
    flag: "https://flagcdn.com/fm.svg",
    areaCode: "+691",
  },
  {
    id: 178,
    name: "Sweden",
    abv: "SE",
    language: "Swedish",
    latlong: "62,15",
    currency: "kr",
    flag: "https://flagcdn.com/se.svg",
    areaCode: "+46",
  },
  {
    id: 179,
    name: "Saint Martin",
    abv: "MF",
    language: "French",
    latlong: "18.0708,63.0501",
    currency: "€",
    flag: "https://flagcdn.com/mf.svg",
    areaCode: "+590",
  },
  {
    id: 180,
    name: "Slovakia",
    abv: "SK",
    language: "Slovak",
    latlong: "48.66666666,19.5",
    currency: "€",
    flag: "https://flagcdn.com/sk.svg",
    areaCode: "+421",
  },
  {
    id: 181,
    name: "DR Congo",
    abv: "CD",
    language: "French",
    latlong: "0,25",
    currency: "FC",
    flag: "https://flagcdn.com/cd.svg",
    areaCode: "+243",
  },
  {
    id: 182,
    name: "Montenegro",
    abv: "ME",
    language: "Montenegrin",
    latlong: "42.5,19.3",
    currency: "€",
    flag: "https://flagcdn.com/me.svg",
    areaCode: "+382",
  },
  {
    id: 183,
    name: "Gibraltar",
    abv: "GI",
    language: "English",
    latlong: "36.13333333,-5.35",
    currency: "£",
    flag: "https://flagcdn.com/gi.svg",
    areaCode: "+350",
  },
  {
    id: 184,
    name: "Somalia",
    abv: "SO",
    language: "Arabic",
    latlong: "10,49",
    currency: "Sh",
    flag: "https://flagcdn.com/so.svg",
    areaCode: "+252",
  },
  {
    id: 185,
    name: "Sri Lanka",
    abv: "LK",
    language: "Sinhala",
    latlong: "7,81",
    currency: "Rs  රු",
    flag: "https://flagcdn.com/lk.svg",
    areaCode: "+94",
  },
  {
    id: 186,
    name: "Cyprus",
    abv: "CY",
    language: "Greek",
    latlong: "35,33",
    currency: "€",
    flag: "https://flagcdn.com/cy.svg",
    areaCode: "+357",
  },
  {
    id: 187,
    name: "Laos",
    abv: "LA",
    language: "Lao",
    latlong: "18,105",
    currency: "₭",
    flag: "https://flagcdn.com/la.svg",
    areaCode: "+856",
  },
  {
    id: 188,
    name: "Morocco",
    abv: "MA",
    language: "Arabic",
    latlong: "32,-5",
    currency: "د.م.",
    flag: "https://flagcdn.com/ma.svg",
    areaCode: "+212",
  },
  {
    id: 189,
    name: "Timor-Leste",
    abv: "TL",
    language: "Portuguese",
    latlong: "-8.83333333,125.91666666",
    currency: "$",
    flag: "https://flagcdn.com/tl.svg",
    areaCode: "+670",
  },
  {
    id: 190,
    name: "Yemen",
    abv: "YE",
    language: "Arabic",
    latlong: "15,48",
    currency: "﷼",
    flag: "https://flagcdn.com/ye.svg",
    areaCode: "+967",
  },
  {
    id: 191,
    name: "Falkland Islands",
    abv: "FK",
    language: "English",
    latlong: "-51.75,-59",
    currency: "£",
    flag: "https://flagcdn.com/fk.svg",
    areaCode: "+500",
  },
  {
    id: 192,
    name: "Equatorial Guinea",
    abv: "GQ",
    language: "French",
    latlong: "2,10",
    currency: "Fr",
    flag: "https://flagcdn.com/gq.svg",
    areaCode: "+240",
  },
  {
    id: 193,
    name: "Algeria",
    abv: "DZ",
    language: "Arabic",
    latlong: "28,3",
    currency: "د.ج",
    flag: "https://flagcdn.com/dz.svg",
    areaCode: "+213",
  },
  {
    id: 194,
    name: "Zambia",
    abv: "ZM",
    language: "English",
    latlong: "-15,30",
    currency: "ZK",
    flag: "https://flagcdn.com/zm.svg",
    areaCode: "+260",
  },
  {
    id: 195,
    name: "Serbia",
    abv: "RS",
    language: "Serbian",
    latlong: "44,21",
    currency: "дин.",
    flag: "https://flagcdn.com/rs.svg",
    areaCode: "+381",
  },
  {
    id: 196,
    name: "Andorra",
    abv: "AD",
    language: "Catalan",
    latlong: "42.5,1.5",
    currency: "€",
    flag: "https://flagcdn.com/ad.svg",
    areaCode: "+376",
  },
  {
    id: 197,
    name: "São Tomé and Príncipe",
    abv: "ST",
    language: "Portuguese",
    latlong: "1,7",
    currency: "Db",
    flag: "https://flagcdn.com/st.svg",
    areaCode: "+239",
  },
  {
    id: 198,
    name: "Djibouti",
    abv: "DJ",
    language: "Arabic",
    latlong: "11.5,43",
    currency: "Fr",
    flag: "https://flagcdn.com/dj.svg",
    areaCode: "+253",
  },
  {
    id: 199,
    name: "Bulgaria",
    abv: "BG",
    language: "Bulgarian",
    latlong: "43,25",
    currency: "лв",
    flag: "https://flagcdn.com/bg.svg",
    areaCode: "+359",
  },
  {
    id: 200,
    name: "United States Virgin Islands",
    abv: "VI",
    language: "English",
    latlong: "18.35,-64.933333",
    currency: "$",
    flag: "https://flagcdn.com/vi.svg",
    areaCode: "+1340",
  },
  {
    id: 201,
    name: "Argentina",
    abv: "AR",
    language: "Guaraní",
    latlong: "-34,-64",
    currency: "$",
    flag: "https://flagcdn.com/ar.svg",
    areaCode: "+54",
  },
  {
    id: 202,
    name: "Nigeria",
    abv: "NG",
    language: "English",
    latlong: "10,8",
    currency: "₦",
    flag: "https://flagcdn.com/ng.svg",
    areaCode: "+234",
  },
  {
    id: 203,
    name: "Rwanda",
    abv: "RW",
    language: "English",
    latlong: "-2,30",
    currency: "Fr",
    flag: "https://flagcdn.com/rw.svg",
    areaCode: "+250",
  },
  {
    id: 204,
    name: "Saint Helena, Ascension and Tristan da Cunha",
    abv: "SH",
    language: "English",
    latlong: "-15.95,-5.72",
    currency: "£",
    flag: "https://flagcdn.com/sh.svg",
    areaCode: "+290",
  },
  {
    id: 205,
    name: "Canada",
    abv: "CA",
    language: "English",
    latlong: "60,-95",
    currency: "$",
    flag: "https://flagcdn.com/ca.svg",
    areaCode: "+1",
  },
  {
    id: 206,
    name: "North Korea",
    abv: "KP",
    language: "Korean",
    latlong: "40,127",
    currency: "₩",
    flag: "https://flagcdn.com/kp.svg",
    areaCode: "+850",
  },
  {
    id: 207,
    name: "Åland Islands",
    abv: "AX",
    language: "Swedish",
    latlong: "60.116667,19.9",
    currency: "€",
    flag: "https://flagcdn.com/ax.svg",
    areaCode: "+35818",
  },
  {
    id: 208,
    name: "North Macedonia",
    abv: "MK",
    language: "Macedonian",
    latlong: "41.83333333,22",
    currency: "den",
    flag: "https://flagcdn.com/mk.svg",
    areaCode: "+389",
  },
  {
    id: 209,
    name: "Netherlands",
    abv: "NL",
    language: "Dutch",
    latlong: "52.5,5.75",
    currency: "€",
    flag: "https://flagcdn.com/nl.svg",
    areaCode: "+31",
  },
  {
    id: 210,
    name: "Niger",
    abv: "NE",
    language: "French",
    latlong: "16,8",
    currency: "Fr",
    flag: "https://flagcdn.com/ne.svg",
    areaCode: "+227",
  },
  {
    id: 211,
    name: "Singapore",
    abv: "SG",
    language: "Chinese",
    latlong: "1.36666666,103.8",
    currency: "$",
    flag: "https://flagcdn.com/sg.svg",
    areaCode: "+65",
  },
  {
    id: 212,
    name: "Chad",
    abv: "TD",
    language: "Arabic",
    latlong: "15,19",
    currency: "Fr",
    flag: "https://flagcdn.com/td.svg",
    areaCode: "+235",
  },
  {
    id: 213,
    name: "Curaçao",
    abv: "CW",
    language: "English",
    latlong: "12.116667,-68.933333",
    currency: "ƒ",
    flag: "https://flagcdn.com/cw.svg",
    areaCode: "+599",
  },
  {
    id: 214,
    name: "Niue",
    abv: "NU",
    language: "English",
    latlong: "-19.03333333,-169.86666666",
    currency: "$",
    flag: "https://flagcdn.com/nu.svg",
    areaCode: "+683",
  },
  {
    id: 215,
    name: "Guinea-Bissau",
    abv: "GW",
    language: "Portuguese",
    latlong: "12,-15",
    currency: "Fr",
    flag: "https://flagcdn.com/gw.svg",
    areaCode: "+245",
  },
  {
    id: 216,
    name: "Nauru",
    abv: "NR",
    language: "English",
    latlong: "-0.53333333,166.91666666",
    currency: "$",
    flag: "https://flagcdn.com/nr.svg",
    areaCode: "+674",
  },
  {
    id: 217,
    name: "Zimbabwe",
    abv: "ZW",
    language: "Chibarwe",
    latlong: "-20,30",
    currency: "$",
    flag: "https://flagcdn.com/zw.svg",
    areaCode: "+263",
  },
  {
    id: 218,
    name: "China",
    abv: "CN",
    language: "Chinese",
    latlong: "35,105",
    currency: "¥",
    flag: "https://flagcdn.com/cn.svg",
    areaCode: "+86",
  },
  {
    id: 219,
    name: "Christmas Island",
    abv: "CX",
    language: "English",
    latlong: "-10.5,105.66666666",
    currency: "$",
    flag: "https://flagcdn.com/cx.svg",
    areaCode: "+61",
  },
  {
    id: 220,
    name: "Puerto Rico",
    abv: "PR",
    language: "English",
    latlong: "18.25,-66.5",
    currency: "$",
    flag: "https://flagcdn.com/pr.svg",
    areaCode: "+1787",
  },
  {
    id: 221,
    name: "Ethiopia",
    abv: "ET",
    language: "Amharic",
    latlong: "8,38",
    currency: "Br",
    flag: "https://flagcdn.com/et.svg",
    areaCode: "+251",
  },
  {
    id: 222,
    name: "Grenada",
    abv: "GD",
    language: "English",
    latlong: "12.11666666,-61.66666666",
    currency: "$",
    flag: "https://flagcdn.com/gd.svg",
    areaCode: "+1473",
  },
  {
    id: 223,
    name: "Finland",
    abv: "FI",
    language: "Finnish",
    latlong: "64,26",
    currency: "€",
    flag: "https://flagcdn.com/fi.svg",
    areaCode: "+358",
  },
  {
    id: 224,
    name: "Turks and Caicos Islands",
    abv: "TC",
    language: "English",
    latlong: "21.75,-71.58333333",
    currency: "$",
    flag: "https://flagcdn.com/tc.svg",
    areaCode: "+1649",
  },
  {
    id: 225,
    name: "Burundi",
    abv: "BI",
    language: "French",
    latlong: "-3.5,30",
    currency: "Fr",
    flag: "https://flagcdn.com/bi.svg",
    areaCode: "+257",
  },
  {
    id: 226,
    name: "Guam",
    abv: "GU",
    language: "Chamorro",
    latlong: "13.46666666,144.78333333",
    currency: "$",
    flag: "https://flagcdn.com/gu.svg",
    areaCode: "+1671",
  },
  {
    id: 227,
    name: "Jordan",
    abv: "JO",
    language: "Arabic",
    latlong: "31,36",
    currency: "د.ا",
    flag: "https://flagcdn.com/jo.svg",
    areaCode: "+962",
  },
  {
    id: 228,
    name: "Mali",
    abv: "ML",
    language: "French",
    latlong: "17,-4",
    currency: "Fr",
    flag: "https://flagcdn.com/ml.svg",
    areaCode: "+223",
  },
  {
    id: 229,
    name: "Ukraine",
    abv: "UA",
    language: "Ukrainian",
    latlong: "49,32",
    currency: "₴",
    flag: "https://flagcdn.com/ua.svg",
    areaCode: "+380",
  },
  {
    id: 230,
    name: "Réunion",
    abv: "RE",
    language: "French",
    latlong: "-21.15,55.5",
    currency: "€",
    flag: "https://flagcdn.com/re.svg",
    areaCode: "+262",
  },
  {
    id: 231,
    name: "Svalbard and Jan Mayen",
    abv: "SJ",
    language: "Norwegian",
    latlong: "78,20",
    currency: "kr",
    flag: "https://flagcdn.com/sj.svg",
    areaCode: "+4779",
  },
  {
    id: 232,
    name: "Cocos (Keeling) Islands",
    abv: "CC",
    language: "English",
    latlong: "12.1642,96.871",
    currency: "$",
    flag: "https://flagcdn.com/cc.svg",
    areaCode: "+61",
  },
  {
    id: 233,
    name: "Tanzania",
    abv: "TZ",
    language: "English",
    latlong: "-6,35",
    currency: "Sh",
    flag: "https://flagcdn.com/tz.svg",
    areaCode: "+255",
  },
  {
    id: 234,
    name: "Qatar",
    abv: "QA",
    language: "Arabic",
    latlong: "25.5,51.25",
    currency: "ر.ق",
    flag: "https://flagcdn.com/qa.svg",
    areaCode: "+974",
  },
  {
    id: 235,
    name: "Brazil",
    abv: "BR",
    language: "Portuguese",
    latlong: "-10,-55",
    currency: "R$",
    flag: "https://flagcdn.com/br.svg",
    areaCode: "+55",
  },
  {
    id: 236,
    name: "Sudan",
    abv: "SD",
    language: "Arabic",
    latlong: "15,30",
    currency: "",
    flag: "https://flagcdn.com/sd.svg",
    areaCode: "+249",
  },
  {
    id: 237,
    name: "Romania",
    abv: "RO",
    language: "Romanian",
    latlong: "46,25",
    currency: "lei",
    flag: "https://flagcdn.com/ro.svg",
    areaCode: "+40",
  },
  {
    id: 238,
    name: "Anguilla",
    abv: "AI",
    language: "English",
    latlong: "18.25,-63.16666666",
    currency: "$",
    flag: "https://flagcdn.com/ai.svg",
    areaCode: "+1264",
  },
  {
    id: 239,
    name: "Iraq",
    abv: "IQ",
    language: "Arabic",
    latlong: "33,44",
    currency: "ع.د",
    flag: "https://flagcdn.com/iq.svg",
    areaCode: "+964",
  },
  {
    id: 240,
    name: "Bhutan",
    abv: "BT",
    language: "Dzongkha",
    latlong: "27.5,90.5",
    currency: "Nu.",
    flag: "https://flagcdn.com/bt.svg",
    areaCode: "+975",
  },
  {
    id: 241,
    name: "Honduras",
    abv: "HN",
    language: "Spanish",
    latlong: "15,-86.5",
    currency: "L",
    flag: "https://flagcdn.com/hn.svg",
    areaCode: "+504",
  },
  {
    id: 242,
    name: "Namibia",
    abv: "NA",
    language: "Afrikaans",
    latlong: "-22,17",
    currency: "$",
    flag: "https://flagcdn.com/na.svg",
    areaCode: "+264",
  },
  {
    id: 243,
    name: "Slovenia",
    abv: "SI",
    language: "Slovene",
    latlong: "46.11666666,14.81666666",
    currency: "€",
    flag: "https://flagcdn.com/si.svg",
    areaCode: "+386",
  },
  {
    id: 244,
    name: "Haiti",
    abv: "HT",
    language: "French",
    latlong: "19,-72.41666666",
    currency: "G",
    flag: "https://flagcdn.com/ht.svg",
    areaCode: "+509",
  },
  {
    id: 245,
    name: "Bosnia and Herzegovina",
    abv: "BA",
    language: "Bosnian",
    latlong: "44,18",
    currency: "",
    flag: "https://flagcdn.com/ba.svg",
    areaCode: "+387",
  },
  {
    id: 246,
    name: "Greenland",
    abv: "GL",
    language: "Greenlandic",
    latlong: "72,-40",
    currency: "kr.",
    flag: "https://flagcdn.com/gl.svg",
    areaCode: "+299",
  },
  {
    id: 247,
    name: "Jamaica",
    abv: "JM",
    language: "English",
    latlong: "18.25,-77.5",
    currency: "$",
    flag: "https://flagcdn.com/jm.svg",
    areaCode: "+1876",
  },
  {
    id: 248,
    name: "Malta",
    abv: "MT",
    language: "English",
    latlong: "35.9375,14.3754",
    currency: "€",
    flag: "https://flagcdn.com/mt.svg",
    areaCode: "+356",
  },
  {
    id: 249,
    name: "Bolivia",
    abv: "BO",
    language: "Aymara",
    latlong: "-17,-65",
    currency: "Bs.",
    flag: "https://flagcdn.com/bo.svg",
    areaCode: "+591",
  },
];
